### ISSUE TITLE
it's "example", not "exemple"

### ISSUE THREAD

**Issue by Goosople** [jihoonkimtech/ClockForSeg_Lib#1]
![image](https://user-images.githubusercontent.com/60741493/202880568-82b4cd82-0792-4f38-96d0-03dfe4dd41e3.png)
Your lib is great, but if you continue to use the typo *"ex**e**mple"* as the folder name, your example program will not be shown in Arduino IDE.

**Comment by jihoonkimtech** [comment]
Thank you, it was modified in version 1.0.2
